artifact_location: file:///Users/ngohongthai/Documents/projects/mlops-tagifai/stores/model/889025912750143693
creation_time: 1687883500538
experiment_id: '889025912750143693'
last_update_time: 1687883500538
lifecycle_stage: active
name: optimization
