artifact_uri: file:///Users/ngohongthai/Documents/projects/mlops-tagifai/stores/model/889025912750143693/d4bfc9c7932c43cea746bdffeff267bb/artifacts
end_time: 1687883515754
entry_point_name: ''
experiment_id: '889025912750143693'
lifecycle_stage: active
run_id: d4bfc9c7932c43cea746bdffeff267bb
run_name: '17'
run_uuid: d4bfc9c7932c43cea746bdffeff267bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1687883515747
status: 3
tags: []
user_id: ngohongthai
